<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign up_emailaddress</name>
   <tag></tag>
   <elementGuidId>47796dac-04ef-4034-9e3a-f73da28cc181</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emailaddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emailaddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Email address&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>421fa423-afaf-4e8c-9e2c-ad4760108a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>34ae959e-8f70-427a-94ea-9bc055cdaeb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.removeAttribute('autocomplete');</value>
      <webElementGuid>ab8f4bdb-041e-4ad3-a91d-ff9b464411db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email address</value>
      <webElementGuid>4f714047-698b-4211-920f-e1805b1d8e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>083f4c48-2dc4-4df2-97f8-9e39930c5d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocusout</name>
      <type>Main</type>
      <value>clearError('1');</value>
      <webElementGuid>387a515b-5d57-40ab-9e70-821432277bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emailaddress</value>
      <webElementGuid>c1a2aca2-ee7e-47c8-bfdb-1dd5737efca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailaddress</value>
      <webElementGuid>1d2b5fb1-61ac-44f7-b86f-af36cf725d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailaddress&quot;)</value>
      <webElementGuid>584639e9-13d5-47d1-b427-0a6dc31c341d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emailaddress']</value>
      <webElementGuid>941f09b5-ad14-4285-992d-5dfee23336b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='bodyclassname']/div[8]/div/main/div/div/div/div[2]/form/div/div/input</value>
      <webElementGuid>04f856f8-10d1-4879-a4f8-7a78d63fee6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b9e1d15f-5188-44fc-a2f6-885f530b4cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Email address' and @name = 'emailaddress' and @id = 'emailaddress']</value>
      <webElementGuid>226b7a73-08d8-4427-82d0-9e30c185d111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='bodyclassname']/div[9]/div/main/div/div/div/div[2]/form/div/div/input</value>
      <webElementGuid>48723f40-acd3-4446-a9da-fedc34c74443</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
