<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i</name>
   <tag></tag>
   <elementGuidId>cf2725c4-5bbc-410a-9e0b-d297a706b4b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.close.js-close-side-nav > i</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='bodyclassname']/aside/div/a[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.close >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2d8fa599-3ad3-4b77-be75-29719ece9f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bodyclassname&quot;)/aside[@class=&quot;c-side-nav&quot;]/div[@class=&quot;action-row&quot;]/a[@class=&quot;close js-close-side-nav&quot;]/i[1]</value>
      <webElementGuid>eaee5e4f-7818-4963-974b-447c8e63caa3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='bodyclassname']/aside/div/a[2]/i</value>
      <webElementGuid>46d08787-28ad-4ff6-9388-d16100acc982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/i</value>
      <webElementGuid>c87540c8-baf0-49cb-a78a-047c4e2bcdd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
