<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_1</name>
   <tag></tag>
   <elementGuidId>76fa5de1-8228-4910-802b-afd7f40cec67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='bodyclassname']/div[7]/header/nav/ul/li[6]/a/span/i[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=&quot;Login/SignUp Look Up a Booking&quot;i >> internal:role=link >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9596fc9a-dc3c-400f-ba73-854e3d7c6bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bodyclassname&quot;)/div[@class=&quot;headerheadache&quot;]/header[@class=&quot;c-main-header&quot;]/nav[@class=&quot;header-links js-header-links&quot;]/ul[1]/li[@class=&quot;user-links has--sub-nav&quot;]/a[@class=&quot;c-menu-btn btn--acount rightBoarder&quot;]/span[@class=&quot;icon-wrap&quot;]/i[2]</value>
      <webElementGuid>e0719882-34fa-4e9e-90e0-310b7bb47b99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='bodyclassname']/div[7]/header/nav/ul/li[6]/a/span/i[2]</value>
      <webElementGuid>7c7f363a-d47f-4c0b-b91f-ff567f63902d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i[2]</value>
      <webElementGuid>cdafd788-3422-4d97-9ff8-7ec3252e42c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
