<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Menu</name>
   <tag></tag>
   <elementGuidId>f794e1bc-9a49-457f-bc3e-e7bc88d6454a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.c-menu-btn.js-open-side-nav > span.icon-wrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='bodyclassname']/div[6]/header/nav/ul/li[7]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a >> internal:has-text=&quot;Menu&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d4ee7e76-202b-40b8-a965-faa43b91e67e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-wrap</value>
      <webElementGuid>c1d2a334-47fd-48f2-96dc-16177bc3991e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menu</value>
      <webElementGuid>55c1d14e-386c-4b5b-8111-fe5a0ce3c983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bodyclassname&quot;)/div[@class=&quot;headerheadache&quot;]/header[@class=&quot;c-main-header&quot;]/nav[@class=&quot;header-links js-header-links&quot;]/ul[1]/li[7]/a[@class=&quot;c-menu-btn js-open-side-nav&quot;]/span[@class=&quot;icon-wrap&quot;]</value>
      <webElementGuid>0dbbfba5-6cb7-4c65-bd3c-192eed45c530</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='bodyclassname']/div[6]/header/nav/ul/li[7]/a/span</value>
      <webElementGuid>6b5ecdfc-c2d6-4f28-abe5-1fad67227142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Look Up a Booking'])[1]/following::span[1]</value>
      <webElementGuid>63bed318-646b-46ce-8009-8f3ad797b649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login/SignUp'])[1]/following::span[1]</value>
      <webElementGuid>eb89c08b-de51-4fe2-aa6b-50894acdf504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a/span</value>
      <webElementGuid>a20cf4a9-0824-42f0-8ca3-f19771e173f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Menu' or . = 'Menu')]</value>
      <webElementGuid>9d9ac711-bcc5-4178-beaf-db74bb428224</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
